### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', core_shared/src/asset/tileset.rs:72:67

### ISSUE THREAD

**Issue by leugengroot** [markusmoenig/Eldiron#4]
Hi,

ran into another problem (if I'm bothering you with there minor issues, just let me know :-) )

Jens

```
❯ cargo run --bin creator
   Compiling core_shared v0.1.0 (/Users/jens/GitHub/Eldiron/core_shared)
   Compiling core_server v0.1.0 (/Users/jens/GitHub/Eldiron/core_server)
   Compiling core_render v0.1.0 (/Users/jens/GitHub/Eldiron/core_render)
   Compiling creator v0.5.5 (/Users/jens/GitHub/Eldiron/creator)
    Finished dev [unoptimized + debuginfo] target(s) in 5.59s
     Running `target/debug/creator`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', core_shared/src/asset/tileset.rs:72:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by markusmoenig** [comment]
Hi again :) No no, happy to get these configuration problems sorted!

Can you get a backtrace where it crashes / what directory is exactly missing ?

**Comment by markusmoenig** [comment]
Yeah, thanks. Git does not commit empty directories.
